package com.golive.config.api.model;

import java.util.Date;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.AreaCode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.AreaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.Active
     *
     * @mbggenerated
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_area.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.ID
     *
     * @return the value of b_system_area.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.ID
     *
     * @param id the value for b_system_area.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.AreaCode
     *
     * @return the value of b_system_area.AreaCode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.AreaCode
     *
     * @param areacode the value for b_system_area.AreaCode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.AreaName
     *
     * @return the value of b_system_area.AreaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.AreaName
     *
     * @param areaname the value for b_system_area.AreaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.Active
     *
     * @return the value of b_system_area.Active
     *
     * @mbggenerated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.Active
     *
     * @param active the value for b_system_area.Active
     *
     * @mbggenerated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.Creator
     *
     * @return the value of b_system_area.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.Creator
     *
     * @param creator the value for b_system_area.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.CreateTime
     *
     * @return the value of b_system_area.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.CreateTime
     *
     * @param createtime the value for b_system_area.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.Modifier
     *
     * @return the value of b_system_area.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.Modifier
     *
     * @param modifier the value for b_system_area.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_area.ModifyTime
     *
     * @return the value of b_system_area.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_area.ModifyTime
     *
     * @param modifytime the value for b_system_area.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}