package com.golive.config.api.model;

import java.util.Date;

public class ClientType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.InstalmentCode
     *
     * @mbggenerated
     */
    private String instalmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.InstalmentName
     *
     * @mbggenerated
     */
    private String instalmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.ManufacturerCode
     *
     * @mbggenerated
     */
    private String manufacturercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.ManufacturerTypeCode
     *
     * @mbggenerated
     */
    private String manufacturertypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.PresentVersion
     *
     * @mbggenerated
     */
    private Short presentversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.LauncherSwitch
     *
     * @mbggenerated
     */
    private Short launcherswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.Play
     *
     * @mbggenerated
     */
    private Short play;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.SpeedLimit
     *
     * @mbggenerated
     */
    private Short speedlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.HardwarePlatformCode
     *
     * @mbggenerated
     */
    private String hardwareplatformcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.LockSwitch
     *
     * @mbggenerated
     */
    private Short lockswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.AdSwitch
     *
     * @mbggenerated
     */
    private Short adswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.SignCoin
     *
     * @mbggenerated
     */
    private Integer signcoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.KdmServerAddressID
     *
     * @mbggenerated
     */
    private String kdmserveraddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.PartnerID
     *
     * @mbggenerated
     */
    private Integer partnerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.Currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.PayType
     *
     * @mbggenerated
     */
    private Short paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.KdmSwitch
     *
     * @mbggenerated
     */
    private Short kdmswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.LicenseProviderCode
     *
     * @mbggenerated
     */
    private String licenseprovidercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_device_clienttype.UseSdcard
     *
     * @mbggenerated
     */
    private Short usesdcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.ID
     *
     * @return the value of b_device_clienttype.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.ID
     *
     * @param id the value for b_device_clienttype.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.InstalmentCode
     *
     * @return the value of b_device_clienttype.InstalmentCode
     *
     * @mbggenerated
     */
    public String getInstalmentcode() {
        return instalmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.InstalmentCode
     *
     * @param instalmentcode the value for b_device_clienttype.InstalmentCode
     *
     * @mbggenerated
     */
    public void setInstalmentcode(String instalmentcode) {
        this.instalmentcode = instalmentcode == null ? null : instalmentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.InstalmentName
     *
     * @return the value of b_device_clienttype.InstalmentName
     *
     * @mbggenerated
     */
    public String getInstalmentname() {
        return instalmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.InstalmentName
     *
     * @param instalmentname the value for b_device_clienttype.InstalmentName
     *
     * @mbggenerated
     */
    public void setInstalmentname(String instalmentname) {
        this.instalmentname = instalmentname == null ? null : instalmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.ManufacturerCode
     *
     * @return the value of b_device_clienttype.ManufacturerCode
     *
     * @mbggenerated
     */
    public String getManufacturercode() {
        return manufacturercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.ManufacturerCode
     *
     * @param manufacturercode the value for b_device_clienttype.ManufacturerCode
     *
     * @mbggenerated
     */
    public void setManufacturercode(String manufacturercode) {
        this.manufacturercode = manufacturercode == null ? null : manufacturercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.ManufacturerTypeCode
     *
     * @return the value of b_device_clienttype.ManufacturerTypeCode
     *
     * @mbggenerated
     */
    public String getManufacturertypecode() {
        return manufacturertypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.ManufacturerTypeCode
     *
     * @param manufacturertypecode the value for b_device_clienttype.ManufacturerTypeCode
     *
     * @mbggenerated
     */
    public void setManufacturertypecode(String manufacturertypecode) {
        this.manufacturertypecode = manufacturertypecode == null ? null : manufacturertypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.Creator
     *
     * @return the value of b_device_clienttype.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.Creator
     *
     * @param creator the value for b_device_clienttype.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.CreateTime
     *
     * @return the value of b_device_clienttype.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.CreateTime
     *
     * @param createtime the value for b_device_clienttype.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.Modifier
     *
     * @return the value of b_device_clienttype.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.Modifier
     *
     * @param modifier the value for b_device_clienttype.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.ModifyTime
     *
     * @return the value of b_device_clienttype.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.ModifyTime
     *
     * @param modifytime the value for b_device_clienttype.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.Description
     *
     * @return the value of b_device_clienttype.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.Description
     *
     * @param description the value for b_device_clienttype.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.PresentVersion
     *
     * @return the value of b_device_clienttype.PresentVersion
     *
     * @mbggenerated
     */
    public Short getPresentversion() {
        return presentversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.PresentVersion
     *
     * @param presentversion the value for b_device_clienttype.PresentVersion
     *
     * @mbggenerated
     */
    public void setPresentversion(Short presentversion) {
        this.presentversion = presentversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.LauncherSwitch
     *
     * @return the value of b_device_clienttype.LauncherSwitch
     *
     * @mbggenerated
     */
    public Short getLauncherswitch() {
        return launcherswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.LauncherSwitch
     *
     * @param launcherswitch the value for b_device_clienttype.LauncherSwitch
     *
     * @mbggenerated
     */
    public void setLauncherswitch(Short launcherswitch) {
        this.launcherswitch = launcherswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.Play
     *
     * @return the value of b_device_clienttype.Play
     *
     * @mbggenerated
     */
    public Short getPlay() {
        return play;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.Play
     *
     * @param play the value for b_device_clienttype.Play
     *
     * @mbggenerated
     */
    public void setPlay(Short play) {
        this.play = play;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.SpeedLimit
     *
     * @return the value of b_device_clienttype.SpeedLimit
     *
     * @mbggenerated
     */
    public Short getSpeedlimit() {
        return speedlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.SpeedLimit
     *
     * @param speedlimit the value for b_device_clienttype.SpeedLimit
     *
     * @mbggenerated
     */
    public void setSpeedlimit(Short speedlimit) {
        this.speedlimit = speedlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.HardwarePlatformCode
     *
     * @return the value of b_device_clienttype.HardwarePlatformCode
     *
     * @mbggenerated
     */
    public String getHardwareplatformcode() {
        return hardwareplatformcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.HardwarePlatformCode
     *
     * @param hardwareplatformcode the value for b_device_clienttype.HardwarePlatformCode
     *
     * @mbggenerated
     */
    public void setHardwareplatformcode(String hardwareplatformcode) {
        this.hardwareplatformcode = hardwareplatformcode == null ? null : hardwareplatformcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.LockSwitch
     *
     * @return the value of b_device_clienttype.LockSwitch
     *
     * @mbggenerated
     */
    public Short getLockswitch() {
        return lockswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.LockSwitch
     *
     * @param lockswitch the value for b_device_clienttype.LockSwitch
     *
     * @mbggenerated
     */
    public void setLockswitch(Short lockswitch) {
        this.lockswitch = lockswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.AdSwitch
     *
     * @return the value of b_device_clienttype.AdSwitch
     *
     * @mbggenerated
     */
    public Short getAdswitch() {
        return adswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.AdSwitch
     *
     * @param adswitch the value for b_device_clienttype.AdSwitch
     *
     * @mbggenerated
     */
    public void setAdswitch(Short adswitch) {
        this.adswitch = adswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.SignCoin
     *
     * @return the value of b_device_clienttype.SignCoin
     *
     * @mbggenerated
     */
    public Integer getSigncoin() {
        return signcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.SignCoin
     *
     * @param signcoin the value for b_device_clienttype.SignCoin
     *
     * @mbggenerated
     */
    public void setSigncoin(Integer signcoin) {
        this.signcoin = signcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.KdmServerAddressID
     *
     * @return the value of b_device_clienttype.KdmServerAddressID
     *
     * @mbggenerated
     */
    public String getKdmserveraddressid() {
        return kdmserveraddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.KdmServerAddressID
     *
     * @param kdmserveraddressid the value for b_device_clienttype.KdmServerAddressID
     *
     * @mbggenerated
     */
    public void setKdmserveraddressid(String kdmserveraddressid) {
        this.kdmserveraddressid = kdmserveraddressid == null ? null : kdmserveraddressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.PartnerID
     *
     * @return the value of b_device_clienttype.PartnerID
     *
     * @mbggenerated
     */
    public Integer getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.PartnerID
     *
     * @param partnerid the value for b_device_clienttype.PartnerID
     *
     * @mbggenerated
     */
    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.Currency
     *
     * @return the value of b_device_clienttype.Currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.Currency
     *
     * @param currency the value for b_device_clienttype.Currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.PayType
     *
     * @return the value of b_device_clienttype.PayType
     *
     * @mbggenerated
     */
    public Short getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.PayType
     *
     * @param paytype the value for b_device_clienttype.PayType
     *
     * @mbggenerated
     */
    public void setPaytype(Short paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.KdmSwitch
     *
     * @return the value of b_device_clienttype.KdmSwitch
     *
     * @mbggenerated
     */
    public Short getKdmswitch() {
        return kdmswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.KdmSwitch
     *
     * @param kdmswitch the value for b_device_clienttype.KdmSwitch
     *
     * @mbggenerated
     */
    public void setKdmswitch(Short kdmswitch) {
        this.kdmswitch = kdmswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.LicenseProviderCode
     *
     * @return the value of b_device_clienttype.LicenseProviderCode
     *
     * @mbggenerated
     */
    public String getLicenseprovidercode() {
        return licenseprovidercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.LicenseProviderCode
     *
     * @param licenseprovidercode the value for b_device_clienttype.LicenseProviderCode
     *
     * @mbggenerated
     */
    public void setLicenseprovidercode(String licenseprovidercode) {
        this.licenseprovidercode = licenseprovidercode == null ? null : licenseprovidercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_device_clienttype.UseSdcard
     *
     * @return the value of b_device_clienttype.UseSdcard
     *
     * @mbggenerated
     */
    public Short getUsesdcard() {
        return usesdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_device_clienttype.UseSdcard
     *
     * @param usesdcard the value for b_device_clienttype.UseSdcard
     *
     * @mbggenerated
     */
    public void setUsesdcard(Short usesdcard) {
        this.usesdcard = usesdcard;
    }
}