package com.golive.config.api.model;

import com.louie.mapper.*;

import java.util.Date;

@Table(name = "b_member_feedbackdefault")
public class FeedBackDefault extends BaseEO {
    @Id
    @Generate
    @Column(name = "ID")
    private Integer id;

    @Column(name = "QuestionCode")
    private String questioncode;

    @Column(name = "QuestionName")
    private String questionname;

    @Column(name = "ClientType")
    private String clienttype;

    @Column(name = "AreaCode")
    private String areacode;

    @Column(name = "ManufacturerCode")
    private String manufacturercode;

    @Column(name = "LanguageCode")
    private String languagecode;

    @Column(name = "Status")
    private Short status;

    @Column(name = "CreateTime")
    private Date createtime;

    @Column(name = "Type")
    private Short type;

    @Column(name = "VersionType")
    private Short versiontype;

    @Column(name = "Creator")
    private String creator;

    @Column(name = "Modifier")
    private String modifier;

    @Column(name = "ModifyTime")
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.ID
     *
     * @return the value of b_member_feedbackdefault.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.ID
     *
     * @param id the value for b_member_feedbackdefault.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.QuestionCode
     *
     * @return the value of b_member_feedbackdefault.QuestionCode
     * @mbggenerated
     */
    public String getQuestioncode() {
        return questioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.QuestionCode
     *
     * @param questioncode the value for b_member_feedbackdefault.QuestionCode
     * @mbggenerated
     */
    public void setQuestioncode(String questioncode) {
        this.questioncode = questioncode == null ? null : questioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.QuestionName
     *
     * @return the value of b_member_feedbackdefault.QuestionName
     * @mbggenerated
     */
    public String getQuestionname() {
        return questionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.QuestionName
     *
     * @param questionname the value for b_member_feedbackdefault.QuestionName
     * @mbggenerated
     */
    public void setQuestionname(String questionname) {
        this.questionname = questionname == null ? null : questionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.ClientType
     *
     * @return the value of b_member_feedbackdefault.ClientType
     * @mbggenerated
     */
    public String getClienttype() {
        return clienttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.ClientType
     *
     * @param clienttype the value for b_member_feedbackdefault.ClientType
     * @mbggenerated
     */
    public void setClienttype(String clienttype) {
        this.clienttype = clienttype == null ? null : clienttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.AreaCode
     *
     * @return the value of b_member_feedbackdefault.AreaCode
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.AreaCode
     *
     * @param areacode the value for b_member_feedbackdefault.AreaCode
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.ManufacturerCode
     *
     * @return the value of b_member_feedbackdefault.ManufacturerCode
     * @mbggenerated
     */
    public String getManufacturercode() {
        return manufacturercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.ManufacturerCode
     *
     * @param manufacturercode the value for b_member_feedbackdefault.ManufacturerCode
     * @mbggenerated
     */
    public void setManufacturercode(String manufacturercode) {
        this.manufacturercode = manufacturercode == null ? null : manufacturercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.LanguageCode
     *
     * @return the value of b_member_feedbackdefault.LanguageCode
     * @mbggenerated
     */
    public String getLanguagecode() {
        return languagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.LanguageCode
     *
     * @param languagecode the value for b_member_feedbackdefault.LanguageCode
     * @mbggenerated
     */
    public void setLanguagecode(String languagecode) {
        this.languagecode = languagecode == null ? null : languagecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.Status
     *
     * @return the value of b_member_feedbackdefault.Status
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.Status
     *
     * @param status the value for b_member_feedbackdefault.Status
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.CreateTime
     *
     * @return the value of b_member_feedbackdefault.CreateTime
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.CreateTime
     *
     * @param createtime the value for b_member_feedbackdefault.CreateTime
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.Type
     *
     * @return the value of b_member_feedbackdefault.Type
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.Type
     *
     * @param type the value for b_member_feedbackdefault.Type
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.VersionType
     *
     * @return the value of b_member_feedbackdefault.VersionType
     * @mbggenerated
     */
    public Short getVersiontype() {
        return versiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.VersionType
     *
     * @param versiontype the value for b_member_feedbackdefault.VersionType
     * @mbggenerated
     */
    public void setVersiontype(Short versiontype) {
        this.versiontype = versiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.Creator
     *
     * @return the value of b_member_feedbackdefault.Creator
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.Creator
     *
     * @param creator the value for b_member_feedbackdefault.Creator
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.Modifier
     *
     * @return the value of b_member_feedbackdefault.Modifier
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.Modifier
     *
     * @param modifier the value for b_member_feedbackdefault.Modifier
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_member_feedbackdefault.ModifyTime
     *
     * @return the value of b_member_feedbackdefault.ModifyTime
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_member_feedbackdefault.ModifyTime
     *
     * @param modifytime the value for b_member_feedbackdefault.ModifyTime
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}