package com.golive.config.api.model;

import java.util.Date;

public class InitiaLization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.InitialiseKey
     *
     * @mbggenerated
     */
    private String initialisekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.InitialiseValue
     *
     * @mbggenerated
     */
    private String initialisevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_initialization.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.ID
     *
     * @return the value of b_system_initialization.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.ID
     *
     * @param id the value for b_system_initialization.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.InitialiseKey
     *
     * @return the value of b_system_initialization.InitialiseKey
     *
     * @mbggenerated
     */
    public String getInitialisekey() {
        return initialisekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.InitialiseKey
     *
     * @param initialisekey the value for b_system_initialization.InitialiseKey
     *
     * @mbggenerated
     */
    public void setInitialisekey(String initialisekey) {
        this.initialisekey = initialisekey == null ? null : initialisekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.InitialiseValue
     *
     * @return the value of b_system_initialization.InitialiseValue
     *
     * @mbggenerated
     */
    public String getInitialisevalue() {
        return initialisevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.InitialiseValue
     *
     * @param initialisevalue the value for b_system_initialization.InitialiseValue
     *
     * @mbggenerated
     */
    public void setInitialisevalue(String initialisevalue) {
        this.initialisevalue = initialisevalue == null ? null : initialisevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.Description
     *
     * @return the value of b_system_initialization.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.Description
     *
     * @param description the value for b_system_initialization.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.Creator
     *
     * @return the value of b_system_initialization.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.Creator
     *
     * @param creator the value for b_system_initialization.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.CreateTime
     *
     * @return the value of b_system_initialization.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.CreateTime
     *
     * @param createtime the value for b_system_initialization.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.Modifier
     *
     * @return the value of b_system_initialization.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.Modifier
     *
     * @param modifier the value for b_system_initialization.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_initialization.ModifyTime
     *
     * @return the value of b_system_initialization.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_initialization.ModifyTime
     *
     * @param modifytime the value for b_system_initialization.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}