package com.golive.config.api.model;

import java.util.Date;

public class Language {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.LanguageID
     *
     * @mbggenerated
     */
    private Integer languageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.LanguageCodes
     *
     * @mbggenerated
     */
    private String languagecodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.Active
     *
     * @mbggenerated
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_language.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.LanguageID
     *
     * @return the value of b_system_language.LanguageID
     *
     * @mbggenerated
     */
    public Integer getLanguageid() {
        return languageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.LanguageID
     *
     * @param languageid the value for b_system_language.LanguageID
     *
     * @mbggenerated
     */
    public void setLanguageid(Integer languageid) {
        this.languageid = languageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.LanguageCodes
     *
     * @return the value of b_system_language.LanguageCodes
     *
     * @mbggenerated
     */
    public String getLanguagecodes() {
        return languagecodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.LanguageCodes
     *
     * @param languagecodes the value for b_system_language.LanguageCodes
     *
     * @mbggenerated
     */
    public void setLanguagecodes(String languagecodes) {
        this.languagecodes = languagecodes == null ? null : languagecodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.Name
     *
     * @return the value of b_system_language.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.Name
     *
     * @param name the value for b_system_language.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.Active
     *
     * @return the value of b_system_language.Active
     *
     * @mbggenerated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.Active
     *
     * @param active the value for b_system_language.Active
     *
     * @mbggenerated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.Creator
     *
     * @return the value of b_system_language.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.Creator
     *
     * @param creator the value for b_system_language.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.CreateTime
     *
     * @return the value of b_system_language.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.CreateTime
     *
     * @param createtime the value for b_system_language.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.Modifier
     *
     * @return the value of b_system_language.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.Modifier
     *
     * @param modifier the value for b_system_language.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_language.ModifyTime
     *
     * @return the value of b_system_language.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_language.ModifyTime
     *
     * @param modifytime the value for b_system_language.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}