package com.golive.config.api.model;

import java.util.Date;

public class MainConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.TerminalConfigID
     *
     * @mbggenerated
     */
    private Integer terminalconfigid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.ResourceUrl
     *
     * @mbggenerated
     */
    private String resourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.UpdateTime
     *
     * @mbggenerated
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.Model
     *
     * @mbggenerated
     */
    private Integer model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_mainconfig.License
     *
     * @mbggenerated
     */
    private Integer license;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.TerminalConfigID
     *
     * @return the value of b_system_mainconfig.TerminalConfigID
     *
     * @mbggenerated
     */
    public Integer getTerminalconfigid() {
        return terminalconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.TerminalConfigID
     *
     * @param terminalconfigid the value for b_system_mainconfig.TerminalConfigID
     *
     * @mbggenerated
     */
    public void setTerminalconfigid(Integer terminalconfigid) {
        this.terminalconfigid = terminalconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Name
     *
     * @return the value of b_system_mainconfig.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Name
     *
     * @param name the value for b_system_mainconfig.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.ResourceUrl
     *
     * @return the value of b_system_mainconfig.ResourceUrl
     *
     * @mbggenerated
     */
    public String getResourceurl() {
        return resourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.ResourceUrl
     *
     * @param resourceurl the value for b_system_mainconfig.ResourceUrl
     *
     * @mbggenerated
     */
    public void setResourceurl(String resourceurl) {
        this.resourceurl = resourceurl == null ? null : resourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.UpdateTime
     *
     * @return the value of b_system_mainconfig.UpdateTime
     *
     * @mbggenerated
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.UpdateTime
     *
     * @param updatetime the value for b_system_mainconfig.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Mark
     *
     * @return the value of b_system_mainconfig.Mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Mark
     *
     * @param mark the value for b_system_mainconfig.Mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Type
     *
     * @return the value of b_system_mainconfig.Type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Type
     *
     * @param type the value for b_system_mainconfig.Type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Creator
     *
     * @return the value of b_system_mainconfig.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Creator
     *
     * @param creator the value for b_system_mainconfig.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.CreateTime
     *
     * @return the value of b_system_mainconfig.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.CreateTime
     *
     * @param createtime the value for b_system_mainconfig.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Modifier
     *
     * @return the value of b_system_mainconfig.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Modifier
     *
     * @param modifier the value for b_system_mainconfig.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.ModifyTime
     *
     * @return the value of b_system_mainconfig.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.ModifyTime
     *
     * @param modifytime the value for b_system_mainconfig.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.Model
     *
     * @return the value of b_system_mainconfig.Model
     *
     * @mbggenerated
     */
    public Integer getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.Model
     *
     * @param model the value for b_system_mainconfig.Model
     *
     * @mbggenerated
     */
    public void setModel(Integer model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_mainconfig.License
     *
     * @return the value of b_system_mainconfig.License
     *
     * @mbggenerated
     */
    public Integer getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_mainconfig.License
     *
     * @param license the value for b_system_mainconfig.License
     *
     * @mbggenerated
     */
    public void setLicense(Integer license) {
        this.license = license;
    }
}