package com.golive.config.api.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.MessageId
     *
     * @mbggenerated
     */
    private Integer messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.AreaCode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.StartTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.EndTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.AuditStatus
     *
     * @mbggenerated
     */
    private Short auditstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.IsShow
     *
     * @mbggenerated
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.ClientType
     *
     * @mbggenerated
     */
    private String clienttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.DisplayTimes
     *
     * @mbggenerated
     */
    private Integer displaytimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.Version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.LanguageCode
     *
     * @mbggenerated
     */
    private String languagecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_message.VersionType
     *
     * @mbggenerated
     */
    private Short versiontype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.MessageId
     *
     * @return the value of b_system_message.MessageId
     *
     * @mbggenerated
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.MessageId
     *
     * @param messageid the value for b_system_message.MessageId
     *
     * @mbggenerated
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Title
     *
     * @return the value of b_system_message.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Title
     *
     * @param title the value for b_system_message.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Message
     *
     * @return the value of b_system_message.Message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Message
     *
     * @param message the value for b_system_message.Message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.AreaCode
     *
     * @return the value of b_system_message.AreaCode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.AreaCode
     *
     * @param areacode the value for b_system_message.AreaCode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.StartTime
     *
     * @return the value of b_system_message.StartTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.StartTime
     *
     * @param starttime the value for b_system_message.StartTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.EndTime
     *
     * @return the value of b_system_message.EndTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.EndTime
     *
     * @param endtime the value for b_system_message.EndTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Source
     *
     * @return the value of b_system_message.Source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Source
     *
     * @param source the value for b_system_message.Source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.AuditStatus
     *
     * @return the value of b_system_message.AuditStatus
     *
     * @mbggenerated
     */
    public Short getAuditstatus() {
        return auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.AuditStatus
     *
     * @param auditstatus the value for b_system_message.AuditStatus
     *
     * @mbggenerated
     */
    public void setAuditstatus(Short auditstatus) {
        this.auditstatus = auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.IsShow
     *
     * @return the value of b_system_message.IsShow
     *
     * @mbggenerated
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.IsShow
     *
     * @param isshow the value for b_system_message.IsShow
     *
     * @mbggenerated
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Creator
     *
     * @return the value of b_system_message.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Creator
     *
     * @param creator the value for b_system_message.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.CreateTime
     *
     * @return the value of b_system_message.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.CreateTime
     *
     * @param createtime the value for b_system_message.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Modifier
     *
     * @return the value of b_system_message.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Modifier
     *
     * @param modifier the value for b_system_message.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.ModifyTime
     *
     * @return the value of b_system_message.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.ModifyTime
     *
     * @param modifytime the value for b_system_message.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.ClientType
     *
     * @return the value of b_system_message.ClientType
     *
     * @mbggenerated
     */
    public String getClienttype() {
        return clienttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.ClientType
     *
     * @param clienttype the value for b_system_message.ClientType
     *
     * @mbggenerated
     */
    public void setClienttype(String clienttype) {
        this.clienttype = clienttype == null ? null : clienttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Status
     *
     * @return the value of b_system_message.Status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Status
     *
     * @param status the value for b_system_message.Status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.DisplayTimes
     *
     * @return the value of b_system_message.DisplayTimes
     *
     * @mbggenerated
     */
    public Integer getDisplaytimes() {
        return displaytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.DisplayTimes
     *
     * @param displaytimes the value for b_system_message.DisplayTimes
     *
     * @mbggenerated
     */
    public void setDisplaytimes(Integer displaytimes) {
        this.displaytimes = displaytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Type
     *
     * @return the value of b_system_message.Type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Type
     *
     * @param type the value for b_system_message.Type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.Version
     *
     * @return the value of b_system_message.Version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.Version
     *
     * @param version the value for b_system_message.Version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.LanguageCode
     *
     * @return the value of b_system_message.LanguageCode
     *
     * @mbggenerated
     */
    public String getLanguagecode() {
        return languagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.LanguageCode
     *
     * @param languagecode the value for b_system_message.LanguageCode
     *
     * @mbggenerated
     */
    public void setLanguagecode(String languagecode) {
        this.languagecode = languagecode == null ? null : languagecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_message.VersionType
     *
     * @return the value of b_system_message.VersionType
     *
     * @mbggenerated
     */
    public Short getVersiontype() {
        return versiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_message.VersionType
     *
     * @param versiontype the value for b_system_message.VersionType
     *
     * @mbggenerated
     */
    public void setVersiontype(Short versiontype) {
        this.versiontype = versiontype;
    }
}