package com.golive.config.api.model;

import java.util.Date;

public class Partner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.PartnerName
     *
     * @mbggenerated
     */
    private String partnername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.PartnerLogo
     *
     * @mbggenerated
     */
    private String partnerlogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Xaxle
     *
     * @mbggenerated
     */
    private Integer xaxle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Yaxle
     *
     * @mbggenerated
     */
    private Integer yaxle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Width
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.ModifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.Type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_system_partner.SortIndex
     *
     * @mbggenerated
     */
    private Integer sortindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.ID
     *
     * @return the value of b_system_partner.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.ID
     *
     * @param id the value for b_system_partner.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.PartnerName
     *
     * @return the value of b_system_partner.PartnerName
     *
     * @mbggenerated
     */
    public String getPartnername() {
        return partnername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.PartnerName
     *
     * @param partnername the value for b_system_partner.PartnerName
     *
     * @mbggenerated
     */
    public void setPartnername(String partnername) {
        this.partnername = partnername == null ? null : partnername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.PartnerLogo
     *
     * @return the value of b_system_partner.PartnerLogo
     *
     * @mbggenerated
     */
    public String getPartnerlogo() {
        return partnerlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.PartnerLogo
     *
     * @param partnerlogo the value for b_system_partner.PartnerLogo
     *
     * @mbggenerated
     */
    public void setPartnerlogo(String partnerlogo) {
        this.partnerlogo = partnerlogo == null ? null : partnerlogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Xaxle
     *
     * @return the value of b_system_partner.Xaxle
     *
     * @mbggenerated
     */
    public Integer getXaxle() {
        return xaxle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Xaxle
     *
     * @param xaxle the value for b_system_partner.Xaxle
     *
     * @mbggenerated
     */
    public void setXaxle(Integer xaxle) {
        this.xaxle = xaxle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Yaxle
     *
     * @return the value of b_system_partner.Yaxle
     *
     * @mbggenerated
     */
    public Integer getYaxle() {
        return yaxle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Yaxle
     *
     * @param yaxle the value for b_system_partner.Yaxle
     *
     * @mbggenerated
     */
    public void setYaxle(Integer yaxle) {
        this.yaxle = yaxle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Height
     *
     * @return the value of b_system_partner.Height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Height
     *
     * @param height the value for b_system_partner.Height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Width
     *
     * @return the value of b_system_partner.Width
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Width
     *
     * @param width the value for b_system_partner.Width
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Creator
     *
     * @return the value of b_system_partner.Creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Creator
     *
     * @param creator the value for b_system_partner.Creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.CreateTime
     *
     * @return the value of b_system_partner.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.CreateTime
     *
     * @param createtime the value for b_system_partner.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Modifier
     *
     * @return the value of b_system_partner.Modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Modifier
     *
     * @param modifier the value for b_system_partner.Modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.ModifyTime
     *
     * @return the value of b_system_partner.ModifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.ModifyTime
     *
     * @param modifytime the value for b_system_partner.ModifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Status
     *
     * @return the value of b_system_partner.Status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Status
     *
     * @param status the value for b_system_partner.Status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.Type
     *
     * @return the value of b_system_partner.Type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.Type
     *
     * @param type the value for b_system_partner.Type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_system_partner.SortIndex
     *
     * @return the value of b_system_partner.SortIndex
     *
     * @mbggenerated
     */
    public Integer getSortindex() {
        return sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_system_partner.SortIndex
     *
     * @param sortindex the value for b_system_partner.SortIndex
     *
     * @mbggenerated
     */
    public void setSortindex(Integer sortindex) {
        this.sortindex = sortindex;
    }
}